services:
  stock-cms-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-cms-client
    expose:
      - "3000"
    env_file:
      - .env.production
    networks:
      - frontend_net
      - backend_net   # gắn cùng network với backend để Nginx thấy API

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    depends_on:
      - stock-cms-client
      - stock-predict-api   # đảm bảo backend sẵn sàng
    networks:
      - frontend_net
      - backend_net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - frontend_net

networks:
  frontend_net:
    driver: bridge
  backend_net:
    external: false 