version: "3"
services:
  stock-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
    ports:
      - "80:3000"
    env_file:
      - .env.production
    depends_on:
      - autobotck_backend-stock-predict-api-1
