services:
  stock-cms-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-cms-client
    expose:
      - "3000"            # expose port nội bộ để nginx proxy, không cần publish ra ngoài
    dns:
      - 8.8.8.8
    env_file:
      - .env.production

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"           # public http
      - "443:443"         # public https (nếu bạn cấu hình SSL)
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - stock-cms-client
